version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - zachferland
  assignees:
  - zachferland
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: "@ethersproject/wallet"
    versions:
    - 5.0.10
    - 5.0.11
    - 5.0.12
  - dependency-name: did-resolver
    versions:
    - 2.1.2
    - 2.2.0
    - 3.0.1
    - 3.0.2
  - dependency-name: ipfs-repo
    versions:
    - 7.0.0
    - 8.0.0
    - 9.0.0
  - dependency-name: is-ipfs
    versions:
    - 2.0.0
    - 3.0.0
    - 4.0.0
  - dependency-name: ipfs
    versions:
    - 0.53.2
    - 0.54.1
    - 0.54.2
  - dependency-name: orbit-db
    versions:
    - 0.26.0
